config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:new, :create]
  resources :tasks, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :content, presence: true, length: { maximum: 15 }
    validates :date, presence: true, length: { maximum: 15 }
    
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
        redirect_to login_url
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to tasks_url
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)  
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  
  def index
    @tasks = current_user.tasks.order(date: :desc)
  end

  def new
    @task = Task.new
    
  end

  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "記録されました。"
      redirect_to tasks_url
    else
      flash[:danger] = "記録に失敗しました。"
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    flash[:success] = "正常に削除されました。"
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def task_params
    params.require(:task).permit(:content, :date, :hour, :minute)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url  
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "登録が完了しました。"
      redirect_to login_url
    else
      flash.now[:danger] = "登録に失敗しました。"
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4 navbar-dark bg-dark">
  <nav class="container navbar navbar-expand-sm navbar-dark bg-dark">
    <%= link_to "Time-manage", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
<% if logged_in? %>
        <li class="nav-item"><%= link_to "活動記録", tasks_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "活動追加", new_task_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: "nav-link" %></li>
        <p class="text-white mt-2 ml-3" ><%= current_user.name %></p>
<% else %>
        <li class="nav-item"><%= link_to "ユーザー登録", new_user_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
<% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>time-manage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
      <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/index.html.erb
<section class="action-memo">
    <h1 class="text-center">活動記録</h1>
    <ul class="mt-4">
    <% before_date = '' %>
    <% @tasks.each do |task| %>
    <% before_date = task.date if before_date.blank? %>
    
    <% if before_date == task.date %>
      <% if task.content == "勉強" %>
        <div class="border bg-info text-white">
            <li class="mt-2 mb-2 ml-2">
                <%= link_to "削除", task_path(task), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-sm btn-delete" %>
                <%= task.date %>
                <%= task.content %>
                <%= "#{task.hour}時間" %>
                <%= "#{task.minute}分" %>
            </li>
        </div>
      <% else %>
        <div class="border">
            <li class="mt-2 mb-2 ml-2">
                <%= link_to "削除", task_path(task), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-sm btn-delete" %>
                <%= task.date %>
                <%= task.content %>
                <%= "#{task.hour}時間" %>
                <%= "#{task.minute}分" %>
            </li>
        </div>
      <% end %>
    <% else %>
    <br><br>
      <% if task.content == "勉強" %>
          <div class="border bg-info text-white">
              <li class="mt-2 mb-2 ml-2">
                  <%= link_to "削除", task_path(task), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-sm btn-delete" %>
                  <%= task.date %>
                  <%= task.content %>
                  <%= "#{task.hour}時間" %>
                  <%= "#{task.minute}分" %>
              </li>
          </div>
        <% else %>
          <div class="border">
              <li class="mt-2 mb-2 ml-2">
                  <%= link_to "削除", task_path(task), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-sm btn-delete" %>
                  <%= task.date %>
                  <%= task.content %>
                  <%= "#{task.hour}時間" %>
                  <%= "#{task.minute}分" %>
              </li>
          </div>
        <% end %>
    <% end %>
    <% before_date = task.date %>
    <% end %>
    </ul>
</div>

app/views/tasks/new.html.erb
<section class="action-new">
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <h1 class="text-center">活動追加</h1>
    <%= form_with(model: @task, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <%= f.label :date, '日付' %>
      <%= f.text_field :date, value: Time.current.strftime("%Y-%m-%d"), class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :content, '活動内容' %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :hour, '時間' %>
      <%= f.select :hour, [['-', '-'],['1時間', '01:00:00'],['2時間', '02:00:00'],['3時間', '03:00:00'],['4時間', '04:00:00'],['5時間', '05:00:00'],['6時間', '06:00:00'],['7時間', '07:00:00'],['8時間', '08:00:00'],['9時間', '09:00:00'],['10時間', '10:00:00']] %>
    </div>
    
    <div class="form-group">
      <%= f.label :minute, '分' %>
    　<%= f.select :minute, [['-', '-'],['10分', '10:00:00'],['20分', '20:00:00'],['30分', '30:00:00'],['40分', '40:00:00'],['50分', '50:00:00']] %>
    </div>
    
      <%= f.submit '記録', class: 'btn btn-primary btn-block' %>
    <% end %>
    
  </div>
</div>
</section>

app/views/toppages/index.html.erb
<section class="top">
    <div class="text-center">
      <h1>Time-manage</h1>
    </div>
<section>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
     <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認用）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'ユーザー登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>